export type ExperienceEntry = {
  company: string
  role: string
  duration: string
}

export type UserProfile = {
  fullName: string
  age: string
  title: string
  location: string
  yearsExperience: string
  summary: string
  skills: string[]
  experiences: ExperienceEntry[]
}

export const inDemandSkills = new Set([
  "ux research",
  "interaction design",
  "design systems",
  "figma",
  "product strategy",
  "frontend",
  "react",
  "typescript",
  "prototyping",
  "user research",
  "product design",
  // Tech / engineering skills
  "javascript",
  "python",
  "java",
  "node.js",
  "next.js",
  "sql",
  "postgresql",
  "mongodb",
  "aws",
  "docker",
  "kubernetes",
  "ci/cd",
  "git",
  "rest apis",
  "graphql",
  "machine learning",
  "deep learning",
  "tensorflow",
  "pytorch",
  "data analysis",
  "pandas",
  "data visualization",
  "android (kotlin)",
  "ios (swift)",
  "flutter",
  "react native",
  "cybersecurity",
  "penetration testing",
  "cloud architecture",
  "terraform",
  "system design",
  "linux",
  "c++",
  "golang",
  "blockchain",
  "solidity",
])

export type OpportunityType = "Job" | "Gig" | "Project" | "Mentorship" | "Internship" | "Club"

export type ClubCategory = "Cultural & Performing Arts" | "Technical & Academic" | "Special Interest & Social" | "Sports"

export type Opportunity = {
  id: string
  type: OpportunityType
  title: string
  org: string
  isNew?: boolean
  match: number
  description: string
  location: string
  pay: string
  commitment: string
  matchedCount: number
  totalSkills: number
  matchedSkills: string[]
  extraSkill?: string
  /** Only set for type === "Club" — groups the club directory into sections. */
  category?: ClubCategory
}

export const stats = [
  { label: "Strong matches", value: "12", note: "85%+ fit", tone: "primary" as const },
  { label: "New this week", value: "5", note: "fresh postings", tone: "amber" as const },
  { label: "Profile strength", value: "82%", note: "add 2 skills", tone: "green" as const },
  { label: "Response rate", value: "68%", note: "from 25 applies", tone: "blue" as const },
]

export const careerOpportunities: Opportunity[] = [
  {
    id: "1",
    type: "Job",
    title: "Senior Product Designer",
    org: "Northwind Health",
    isNew: true,
    match: 94,
    description:
      "Own end-to-end design for a patient-facing scheduling product. Partner closely with research and a small platform team.",
    location: "Remote (EU)",
    pay: "€78k–€95k",
    commitment: "Full-time",
    matchedCount: 4,
    totalSkills: 5,
    matchedSkills: ["Interaction Design", "UX Research", "Design Systems", "Product Strategy"],
    extraSkill: "Accessibility",
  },
  {
    id: "2",
    type: "Gig",
    title: "Design System Lead (Contract)",
    org: "Cobalt Labs",
    isNew: true,
    match: 88,
    description:
      "Stand up a token-based design system across web and mobile. 3-month engagement with option to extend.",
    location: "Remote",
    pay: "€600/day",
    commitment: "3 months · 4 days/wk",
    matchedCount: 4,
    totalSkills: 4,
    matchedSkills: ["Design Systems", "Figma", "Frontend (React)", "Facilitation"],
  },
  {
    id: "3",
    type: "Job",
    title: "Founding Designer",
    org: "Tuple (Seed)",
    match: 81,
    description:
      "First design hire at an AI-for-ops startup. Shape the product, brand, and design culture from the ground up.",
    location: "Hybrid (Berlin)",
    pay: "€70k + equity",
    commitment: "Full-time",
    matchedCount: 3,
    totalSkills: 5,
    matchedSkills: ["Product Strategy", "Prototyping", "Figma"],
    extraSkill: "Brand",
  },
  {
    id: "4",
    type: "Mentorship",
    title: "Mentor a junior designer",
    org: "ADPList Community",
    match: 76,
    description:
      "Give back 1 hour a week guiding an early-career designer through portfolio reviews and career questions.",
    location: "Remote",
    pay: "Volunteer",
    commitment: "1 hr/week",
    matchedCount: 3,
    totalSkills: 4,
    matchedSkills: ["Mentorship", "UX Research", "Portfolio Review"],
  },
  {
    id: "5",
    type: "Project",
    title: "Redesign a nonprofit donation flow",
    org: "GiveWell Collective",
    match: 79,
    description:
      "Short collaborative project to improve conversion on a recurring-donation flow. Great for portfolio impact.",
    location: "Remote",
    pay: "Stipend €1.5k",
    commitment: "4 weeks",
    matchedCount: 3,
    totalSkills: 4,
    matchedSkills: ["Interaction Design", "Prototyping", "UX Research"],
    extraSkill: "Analytics",
  },
  {
    id: "6",
    type: "Gig",
    title: "Usability testing sprint",
    org: "Meridian Fintech",
    match: 73,
    description:
      "Run a two-week moderated usability study on a new onboarding flow and deliver prioritized recommendations.",
    location: "Remote (US overlap)",
    pay: "€450/day",
    commitment: "2 weeks",
    matchedCount: 2,
    totalSkills: 4,
    matchedSkills: ["UX Research", "Facilitation"],
    extraSkill: "Reporting",
  },
  {
    id: "7",
    type: "Internship",
    title: "Product Design Intern",
    org: "Northwind Health",
    isNew: true,
    match: 84,
    description:
      "Support the product design team on a patient scheduling product — wireframes, prototypes, and usability testing alongside senior designers.",
    location: "Remote (EU)",
    pay: "€1.4k/month",
    commitment: "3 months · Full-time",
    matchedCount: 3,
    totalSkills: 5,
    matchedSkills: ["Figma", "Prototyping", "UX Research"],
    extraSkill: "Design Systems",
  },
  {
    id: "8",
    type: "Internship",
    title: "Frontend Engineering Intern",
    org: "Cobalt Labs",
    isNew: true,
    match: 77,
    description:
      "Build and ship UI components for a design-system-driven web app. Pairs closely with design and backend engineers.",
    location: "Remote",
    pay: "€1.1k/month",
    commitment: "3 months · Full-time",
    matchedCount: 2,
    totalSkills: 4,
    matchedSkills: ["Frontend (React)", "Figma"],
    extraSkill: "TypeScript",
  },
  {
    id: "9",
    type: "Internship",
    title: "Data & Insights Intern",
    org: "Meridian Fintech",
    match: 62,
    description:
      "Turn product usage and research data into digestible insights for the design and product teams. Great fit alongside a UX research background.",
    location: "Remote (US overlap)",
    pay: "€1k/month",
    commitment: "2 months · Part-time",
    matchedCount: 1,
    totalSkills: 4,
    matchedSkills: ["UX Research"],
    extraSkill: "Data Analysis",
  },
  {
    id: "10",
    type: "Job",
    title: "UX Researcher",
    org: "Tuple (Seed)",
    match: 86,
    description:
      "Own qualitative and quantitative research for an early-stage product team, feeding findings directly into roadmap decisions.",
    location: "Hybrid (Berlin)",
    pay: "€62k–€74k",
    commitment: "Full-time",
    matchedCount: 3,
    totalSkills: 4,
    matchedSkills: ["UX Research", "Interaction Design", "Product Strategy"],
    extraSkill: "Analytics",
  },
  {
    id: "11",
    type: "Job",
    title: "Product Designer, Growth",
    org: "GiveWell Collective",
    match: 80,
    description:
      "Design and test flows aimed at improving conversion and retention across the donation product, working closely with growth engineering.",
    location: "Remote",
    pay: "€65k–€80k",
    commitment: "Full-time",
    matchedCount: 3,
    totalSkills: 5,
    matchedSkills: ["Interaction Design", "Prototyping", "Product Strategy"],
    extraSkill: "A/B Testing",
  },
  {
    id: "12",
    type: "Job",
    title: "Frontend Developer",
    org: "Northwind Health",
    isNew: true,
    match: 90,
    description:
      "Build accessible, performant interfaces for a patient-facing web app using React and TypeScript, working closely with design and backend teams.",
    location: "Remote (EU)",
    pay: "€55k–€75k",
    commitment: "Full-time",
    matchedCount: 4,
    totalSkills: 5,
    matchedSkills: ["React", "TypeScript", "JavaScript", "REST APIs"],
    extraSkill: "Next.js",
  },
  {
    id: "13",
    type: "Job",
    title: "Backend Developer",
    org: "Meridian Fintech",
    match: 87,
    description:
      "Design and maintain server-side services and APIs that power core fintech workflows, with a strong emphasis on reliability and data integrity.",
    location: "Remote (US overlap)",
    pay: "€60k–€82k",
    commitment: "Full-time",
    matchedCount: 4,
    totalSkills: 5,
    matchedSkills: ["Node.js", "SQL", "PostgreSQL", "REST APIs"],
    extraSkill: "Docker",
  },
  {
    id: "14",
    type: "Job",
    title: "Full Stack Engineer",
    org: "Cobalt Labs",
    isNew: true,
    match: 89,
    description:
      "Own features end-to-end across a Next.js frontend and a Node.js backend, shipping fast in a small, senior engineering team.",
    location: "Remote",
    pay: "€65k–€90k",
    commitment: "Full-time",
    matchedCount: 4,
    totalSkills: 6,
    matchedSkills: ["React", "Node.js", "TypeScript", "SQL"],
    extraSkill: "AWS",
  },
  {
    id: "15",
    type: "Job",
    title: "Data Scientist",
    org: "Meridian Fintech",
    match: 85,
    description:
      "Build predictive models for fraud detection and credit risk, partnering with engineering to ship models into production.",
    location: "Remote (US overlap)",
    pay: "€70k–€95k",
    commitment: "Full-time",
    matchedCount: 3,
    totalSkills: 5,
    matchedSkills: ["Python", "Machine Learning", "Data Analysis"],
    extraSkill: "Pandas",
  },
  {
    id: "16",
    type: "Job",
    title: "Machine Learning Engineer",
    org: "Tuple (Seed)",
    match: 83,
    description:
      "Take ML prototypes from notebook to production, building training pipelines and serving infrastructure for an AI-for-ops product.",
    location: "Hybrid (Berlin)",
    pay: "€75k–€100k + equity",
    commitment: "Full-time",
    matchedCount: 3,
    totalSkills: 5,
    matchedSkills: ["Python", "PyTorch", "Machine Learning"],
    extraSkill: "Docker",
  },
  {
    id: "17",
    type: "Job",
    title: "DevOps Engineer",
    org: "Cobalt Labs",
    match: 82,
    description:
      "Own CI/CD pipelines, container infrastructure, and cloud environments so product teams can ship safely and often.",
    location: "Remote",
    pay: "€68k–€88k",
    commitment: "Full-time",
    matchedCount: 3,
    totalSkills: 5,
    matchedSkills: ["Docker", "Kubernetes", "AWS"],
    extraSkill: "Terraform",
  },
  {
    id: "18",
    type: "Job",
    title: "Cloud Infrastructure Engineer",
    org: "Northwind Health",
    match: 80,
    description:
      "Design and manage the cloud architecture behind a healthcare platform, with a focus on scalability, security, and compliance.",
    location: "Remote (EU)",
    pay: "€70k–€92k",
    commitment: "Full-time",
    matchedCount: 3,
    totalSkills: 5,
    matchedSkills: ["AWS", "Terraform", "Cloud Architecture"],
    extraSkill: "Kubernetes",
  },
  {
    id: "19",
    type: "Job",
    title: "Mobile Developer (React Native)",
    org: "GiveWell Collective",
    match: 78,
    description:
      "Build and maintain the cross-platform mobile app used by donors and field teams, shipping features across iOS and Android.",
    location: "Remote",
    pay: "€58k–€78k",
    commitment: "Full-time",
    matchedCount: 3,
    totalSkills: 4,
    matchedSkills: ["React Native", "JavaScript", "TypeScript"],
    extraSkill: "REST APIs",
  },
  {
    id: "20",
    type: "Job",
    title: "iOS Engineer",
    org: "Tuple (Seed)",
    match: 76,
    description:
      "Build the native iOS client for an AI-for-ops product from the ground up alongside the founding engineering team.",
    location: "Hybrid (Berlin)",
    pay: "€65k–€85k + equity",
    commitment: "Full-time",
    matchedCount: 2,
    totalSkills: 4,
    matchedSkills: ["iOS (Swift)", "Git"],
    extraSkill: "REST APIs",
  },
  {
    id: "21",
    type: "Job",
    title: "Android Engineer",
    org: "GiveWell Collective",
    match: 75,
    description:
      "Own the Android app for a nonprofit donation platform, focused on smooth performance on low-end devices.",
    location: "Remote",
    pay: "€55k–€75k",
    commitment: "Full-time",
    matchedCount: 2,
    totalSkills: 4,
    matchedSkills: ["Android (Kotlin)", "Git"],
    extraSkill: "REST APIs",
  },
  {
    id: "22",
    type: "Job",
    title: "QA / Test Automation Engineer",
    org: "Meridian Fintech",
    match: 74,
    description:
      "Build and maintain automated test suites across web and API layers, and help engineering ship with confidence.",
    location: "Remote (US overlap)",
    pay: "€50k–€68k",
    commitment: "Full-time",
    matchedCount: 2,
    totalSkills: 4,
    matchedSkills: ["CI/CD", "Git"],
    extraSkill: "SQL",
  },
  {
    id: "23",
    type: "Job",
    title: "Cybersecurity Analyst",
    org: "Meridian Fintech",
    match: 79,
    description:
      "Monitor, investigate, and respond to security incidents across fintech infrastructure, and run regular vulnerability assessments.",
    location: "Remote (US overlap)",
    pay: "€65k–€85k",
    commitment: "Full-time",
    matchedCount: 2,
    totalSkills: 4,
    matchedSkills: ["Cybersecurity", "Linux"],
    extraSkill: "Penetration Testing",
  },
  {
    id: "24",
    type: "Job",
    title: "Site Reliability Engineer",
    org: "Cobalt Labs",
    match: 81,
    description:
      "Keep production systems reliable and fast — on-call rotation, incident response, and building tooling to prevent repeat issues.",
    location: "Remote",
    pay: "€72k–€95k",
    commitment: "Full-time",
    matchedCount: 3,
    totalSkills: 5,
    matchedSkills: ["Kubernetes", "Docker", "Linux"],
    extraSkill: "System Design",
  },
  {
    id: "25",
    type: "Internship",
    title: "Software Engineering Intern",
    org: "Cobalt Labs",
    isNew: true,
    match: 80,
    description:
      "Ship real features in a Next.js/TypeScript codebase alongside senior engineers, with regular code review and mentorship.",
    location: "Remote",
    pay: "€1.2k/month",
    commitment: "3 months · Full-time",
    matchedCount: 3,
    totalSkills: 5,
    matchedSkills: ["JavaScript", "React", "Git"],
    extraSkill: "TypeScript",
  },
  {
    id: "26",
    type: "Internship",
    title: "Backend Engineering Intern",
    org: "Meridian Fintech",
    match: 74,
    description:
      "Work on internal APIs and data pipelines for a fintech product, learning production backend practices from a senior team.",
    location: "Remote (US overlap)",
    pay: "€1k/month",
    commitment: "3 months · Full-time",
    matchedCount: 2,
    totalSkills: 4,
    matchedSkills: ["Python", "SQL"],
    extraSkill: "REST APIs",
  },
  {
    id: "27",
    type: "Internship",
    title: "Machine Learning Intern",
    org: "Tuple (Seed)",
    isNew: true,
    match: 76,
    description:
      "Help build and evaluate ML models for an AI-for-ops product, working directly with the founding technical team.",
    location: "Hybrid (Berlin)",
    pay: "€1.3k/month",
    commitment: "3 months · Full-time",
    matchedCount: 2,
    totalSkills: 4,
    matchedSkills: ["Python", "Machine Learning"],
    extraSkill: "PyTorch",
  },
  {
    id: "28",
    type: "Internship",
    title: "Cloud/DevOps Intern",
    org: "Northwind Health",
    match: 68,
    description:
      "Support the platform team with cloud infrastructure tasks, monitoring, and CI/CD pipeline improvements.",
    location: "Remote (EU)",
    pay: "€1k/month",
    commitment: "2 months · Full-time",
    matchedCount: 2,
    totalSkills: 4,
    matchedSkills: ["AWS", "Docker"],
    extraSkill: "CI/CD",
  },
  {
    id: "29",
    type: "Gig",
    title: "API Integration Contract",
    org: "GiveWell Collective",
    match: 72,
    description:
      "Build a set of third-party payment and CRM integrations for the donation platform over a focused 6-week engagement.",
    location: "Remote",
    pay: "€500/day",
    commitment: "6 weeks",
    matchedCount: 2,
    totalSkills: 4,
    matchedSkills: ["Node.js", "REST APIs"],
    extraSkill: "SQL",
  },
  {
    id: "30",
    type: "Gig",
    title: "Data Pipeline Cleanup (Contract)",
    org: "Meridian Fintech",
    match: 70,
    description:
      "Refactor and document a set of brittle ETL scripts into a maintainable data pipeline over a short contract.",
    location: "Remote (US overlap)",
    pay: "€520/day",
    commitment: "1 month",
    matchedCount: 2,
    totalSkills: 4,
    matchedSkills: ["Python", "SQL"],
    extraSkill: "Data Analysis",
  },
  {
    id: "31",
    type: "Project",
    title: "Build an internal analytics dashboard",
    org: "Cobalt Labs",
    match: 75,
    description:
      "Short project to design and build a lightweight internal dashboard visualizing product usage data — great portfolio piece.",
    location: "Remote",
    pay: "Stipend €1.2k",
    commitment: "4 weeks",
    matchedCount: 3,
    totalSkills: 4,
    matchedSkills: ["React", "Data Visualization", "JavaScript"],
    extraSkill: "SQL",
  },
  {
    id: "32",
    type: "Mentorship",
    title: "Mentor a junior software engineer",
    org: "ADPList Community",
    match: 74,
    description:
      "Give back 1 hour a week guiding an early-career engineer through code reviews, system design basics, and career questions.",
    location: "Remote",
    pay: "Volunteer",
    commitment: "1 hr/week",
    matchedCount: 2,
    totalSkills: 4,
    matchedSkills: ["Mentorship", "System Design"],
    extraSkill: "Git",
  },
]

export const clubs: Opportunity[] = [
  // Cultural & Performing Arts
  {
    id: "club-001",
    type: "Club",
    title: "Classical Dance Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in classical dance.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Classical Dance", "Performance", "Choreography"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-002",
    type: "Club",
    title: "Western Dance Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in western dance.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Western Dance", "Choreography", "Performance"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-003",
    type: "Club",
    title: "Regional Dance Club (South Indian)",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in south indian dance.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["South Indian Dance", "Regional Dance", "Performance"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-004",
    type: "Club",
    title: "Regional, Classical & Creative Dance Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in regional dance.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Regional Dance", "Classical Dance", "Creative Movement"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-005",
    type: "Club",
    title: "Classical Fusion & Folk Dance Club — Giddha, Sammi & Luddi",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in giddha.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 4,
    totalSkills: 4,
    matchedSkills: ["Giddha", "Sammi", "Luddi", "Folk Dance"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-006",
    type: "Club",
    title: "Punjabi Folk Dance Club — Bhangra, Jhummar & Malwai Gidha",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in bhangra.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 4,
    totalSkills: 4,
    matchedSkills: ["Bhangra", "Jhummar", "Malwai Gidha", "Folk Dance"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-007",
    type: "Club",
    title: "Tabla Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in tabla.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Tabla", "Percussion", "Indian Classical Music"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-008",
    type: "Club",
    title: "Guitar Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in guitar.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Guitar", "Music", "Performance"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-009",
    type: "Club",
    title: "Drums Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in drums.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Drums", "Percussion", "Music"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-010",
    type: "Club",
    title: "Classical Vocal Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in classical vocals.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Classical Vocals", "Indian Classical Music", "Singing"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-011",
    type: "Club",
    title: "Western Singing & Light Vocal Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in western vocals.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Western Vocals", "Singing", "Music"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-012",
    type: "Club",
    title: "Folk & Indian Instrumental Music Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in folk music.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Folk Music", "Indian Instruments", "Music"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-013",
    type: "Club",
    title: "Acting Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in acting.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Acting", "Theatre", "Performance"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-014",
    type: "Club",
    title: "Mime Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in mime.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Mime", "Theatre", "Performance"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-015",
    type: "Club",
    title: "Skit Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in skit writing.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Skit Writing", "Theatre", "Performance"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-016",
    type: "Club",
    title: "Mimicry & Stand-Up Comedy Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in mimicry.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Mimicry", "Stand-Up Comedy", "Public Speaking"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-017",
    type: "Club",
    title: "Public Speaking & Anchoring Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in public speaking.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Public Speaking", "Anchoring", "Communication"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-018",
    type: "Club",
    title: "Quiz, Poetry & Book Discussion Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in quizzing.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Quizzing", "Poetry", "Literature"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-019",
    type: "Club",
    title: "Publication Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in writing.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Writing", "Editing", "Publication"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-020",
    type: "Club",
    title: "Uni TV Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in broadcasting.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Broadcasting", "Video Production", "Media"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-021",
    type: "Club",
    title: "Folk Arts, Mehendi, Rangoli, Photography & Installation Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in mehendi.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 4,
    totalSkills: 4,
    matchedSkills: ["Mehendi", "Rangoli", "Photography", "Folk Art"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-022",
    type: "Club",
    title: "On-Spot Painting, Poster Making, Collage Making, Clay Modelling & Cartooning Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in painting.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 4,
    totalSkills: 4,
    matchedSkills: ["Painting", "Poster Making", "Clay Modelling", "Cartooning"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-023",
    type: "Club",
    title: "Jhankaar Music Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in music.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Music", "Performance", "Ensemble"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-024",
    type: "Club",
    title: "Drama Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in drama.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Drama", "Theatre", "Scriptwriting"],
    category: "Cultural & Performing Arts",
  },
  {
    id: "club-025",
    type: "Club",
    title: "Fashion Club",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Cultural & Performing Arts. Open to all students interested in fashion design.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Fashion Design", "Styling", "Ramp Walk"],
    category: "Cultural & Performing Arts",
  },
  // Technical & Academic
  {
    id: "club-026",
    type: "Club",
    title: "Tech Army",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Technical & Academic. Open to all students interested in technology.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Technology", "Innovation", "Hackathons"],
    category: "Technical & Academic",
  },
  {
    id: "club-027",
    type: "Club",
    title: "Oasis — Cybersecurity",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Technical & Academic. Open to all students interested in cybersecurity.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Cybersecurity", "Ethical Hacking", "Networking"],
    category: "Technical & Academic",
  },
  {
    id: "club-028",
    type: "Club",
    title: "Reptilian Robotics",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Technical & Academic. Open to all students interested in robotics.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Robotics", "Embedded Systems", "Engineering"],
    category: "Technical & Academic",
  },
  {
    id: "club-029",
    type: "Club",
    title: "Microsoft Student Chapter",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Technical & Academic. Open to all students interested in cloud computing.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Cloud Computing", "Microsoft Technologies", "Developer Community"],
    category: "Technical & Academic",
  },
  {
    id: "club-030",
    type: "Club",
    title: "LPU SAEINDIA Collegiate Club (LSCC)",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Technical & Academic. Open to all students interested in automotive engineering.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Automotive Engineering", "SAE", "Mechanical Design"],
    category: "Technical & Academic",
  },
  {
    id: "club-031",
    type: "Club",
    title: "Coding Blocks",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Technical & Academic. Open to all students interested in competitive programming.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Competitive Programming", "DSA", "Coding"],
    category: "Technical & Academic",
  },
  {
    id: "club-032",
    type: "Club",
    title: "Departmental & Academic Student Organisations",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Technical & Academic. Open to all students interested in academics.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Academics", "Research", "Departmental Events"],
    category: "Technical & Academic",
  },
  // Special Interest & Social
  {
    id: "club-033",
    type: "Club",
    title: "KHOJ — Find Your Real Hero",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Special Interest & Social. Open to all students interested in talent hunt.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Talent Hunt", "Self-Discovery", "Events"],
    category: "Special Interest & Social",
  },
  {
    id: "club-034",
    type: "Club",
    title: "Anicos — Anime",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Special Interest & Social. Open to all students interested in anime.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Anime", "Manga", "Fan Community"],
    category: "Special Interest & Social",
  },
  {
    id: "club-035",
    type: "Club",
    title: "Zenith Minds",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Special Interest & Social. Open to all students interested in leadership.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Leadership", "Personal Development", "Community"],
    category: "Special Interest & Social",
  },
  {
    id: "club-036",
    type: "Club",
    title: "Rotaract Club LPU",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Special Interest & Social. Open to all students interested in community service.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Community Service", "Leadership", "Social Work"],
    category: "Special Interest & Social",
  },
  {
    id: "club-037",
    type: "Club",
    title: "Democrats",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Special Interest & Social. Open to all students interested in debate.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Debate", "Politics", "Public Affairs"],
    category: "Special Interest & Social",
  },
  {
    id: "club-038",
    type: "Club",
    title: "LPU NSS Unit Udaan",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Special Interest & Social. Open to all students interested in social service.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Social Service", "Volunteering", "Community Outreach"],
    category: "Special Interest & Social",
  },
  {
    id: "club-039",
    type: "Club",
    title: "Tachyons",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Special Interest & Social. Open to all students interested in science communication.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Science Communication", "Innovation", "Ideas"],
    category: "Special Interest & Social",
  },
  {
    id: "club-040",
    type: "Club",
    title: "LPU NSS",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Special Interest & Social. Open to all students interested in national service scheme.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["National Service Scheme", "Volunteering", "Social Work"],
    category: "Special Interest & Social",
  },
  {
    id: "club-041",
    type: "Club",
    title: "NCC",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Special Interest & Social. Open to all students interested in national cadet corps.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["National Cadet Corps", "Discipline", "Leadership"],
    category: "Special Interest & Social",
  },
  // Sports
  {
    id: "club-042",
    type: "Club",
    title: "American Football",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in american football.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["American Football", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-043",
    type: "Club",
    title: "Archery",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in archery.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Archery", "Precision", "Individual Sport"],
    category: "Sports",
  },
  {
    id: "club-044",
    type: "Club",
    title: "Athletics",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in athletics.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Athletics", "Track & Field", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-045",
    type: "Club",
    title: "Badminton",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in badminton.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Badminton", "Racquet Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-046",
    type: "Club",
    title: "Baseball",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in baseball.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Baseball", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-047",
    type: "Club",
    title: "Basketball",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in basketball.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Basketball", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-048",
    type: "Club",
    title: "Boxing",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in boxing.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Boxing", "Combat Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-049",
    type: "Club",
    title: "Canoeing & Kayaking",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in canoeing.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Canoeing", "Kayaking", "Water Sport"],
    category: "Sports",
  },
  {
    id: "club-050",
    type: "Club",
    title: "Chess",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in chess.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Chess", "Strategy", "Individual Sport"],
    category: "Sports",
  },
  {
    id: "club-051",
    type: "Club",
    title: "Cricket",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in cricket.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Cricket", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-052",
    type: "Club",
    title: "Cycling",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in cycling.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Cycling", "Endurance", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-053",
    type: "Club",
    title: "Dodge/Drop Roball",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in roball.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Roball", "Dodgeball", "Team Sport"],
    category: "Sports",
  },
  {
    id: "club-054",
    type: "Club",
    title: "Fencing",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in fencing.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Fencing", "Combat Sport", "Precision"],
    category: "Sports",
  },
  {
    id: "club-055",
    type: "Club",
    title: "Football",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in football.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Football", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-056",
    type: "Club",
    title: "Grappling Sports",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in grappling.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Grappling", "Combat Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-057",
    type: "Club",
    title: "Gymnastics",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in gymnastics.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Gymnastics", "Flexibility", "Individual Sport"],
    category: "Sports",
  },
  {
    id: "club-058",
    type: "Club",
    title: "Handball",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in handball.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Handball", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-059",
    type: "Club",
    title: "Hockey",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in hockey.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Hockey", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-060",
    type: "Club",
    title: "Judo",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in judo.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Judo", "Combat Sport", "Martial Arts"],
    category: "Sports",
  },
  {
    id: "club-061",
    type: "Club",
    title: "Kabaddi",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in kabaddi.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Kabaddi", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-062",
    type: "Club",
    title: "Kabaddi (National Style)",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in kabaddi.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Kabaddi", "National Style", "Team Sport"],
    category: "Sports",
  },
  {
    id: "club-063",
    type: "Club",
    title: "Karate",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in karate.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Karate", "Martial Arts", "Combat Sport"],
    category: "Sports",
  },
  {
    id: "club-064",
    type: "Club",
    title: "Kho Kho",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in kho kho.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Kho Kho", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-065",
    type: "Club",
    title: "Kickboxing",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in kickboxing.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Kickboxing", "Combat Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-066",
    type: "Club",
    title: "Netball",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in netball.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Netball", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-067",
    type: "Club",
    title: "Pencak Silat",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in pencak silat.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Pencak Silat", "Martial Arts", "Combat Sport"],
    category: "Sports",
  },
  {
    id: "club-068",
    type: "Club",
    title: "Roller Sports",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in roller skating.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Roller Skating", "Roller Sports", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-069",
    type: "Club",
    title: "Rowing",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in rowing.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Rowing", "Endurance", "Water Sport"],
    category: "Sports",
  },
  {
    id: "club-070",
    type: "Club",
    title: "Rugby",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in rugby.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Rugby", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-071",
    type: "Club",
    title: "Sepak Takraw",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in sepak takraw.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Sepak Takraw", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-072",
    type: "Club",
    title: "Table Tennis",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in table tennis.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Table Tennis", "Racquet Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-073",
    type: "Club",
    title: "Taekwondo",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in taekwondo.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Taekwondo", "Martial Arts", "Combat Sport"],
    category: "Sports",
  },
  {
    id: "club-074",
    type: "Club",
    title: "Volleyball",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in volleyball.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Volleyball", "Team Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-075",
    type: "Club",
    title: "Weightlifting",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in weightlifting.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Weightlifting", "Strength Training", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-076",
    type: "Club",
    title: "Wrestling",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in wrestling.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Wrestling", "Combat Sport", "Fitness"],
    category: "Sports",
  },
  {
    id: "club-077",
    type: "Club",
    title: "Wushu",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in wushu.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Wushu", "Martial Arts", "Combat Sport"],
    category: "Sports",
  },
  {
    id: "club-078",
    type: "Club",
    title: "Aquatics — Swimming, Diving & Water Polo",
    org: "LPU Student Clubs",
    match: 68,
    description: "LPU student club — Sports. Open to all students interested in swimming.",
    location: "On campus (LPU)",
    pay: "No cost",
    commitment: "Weekly sessions",
    matchedCount: 3,
    totalSkills: 3,
    matchedSkills: ["Swimming", "Diving", "Water Polo"],
    category: "Sports",
  },
]

export const clubCategories: ClubCategory[] = [
  "Cultural & Performing Arts",
  "Technical & Academic",
  "Special Interest & Social",
  "Sports",
]

// Full catalog shown in the app and used for AI-coach matching: jobs, internships,
// gigs, projects, and mentorships, plus the campus club directory.
export const opportunities: Opportunity[] = [...careerOpportunities, ...clubs]

export const skills = [
  { name: "UX Research", level: 92, inDemand: true },
  { name: "Interaction Design", level: 88, inDemand: true },
  { name: "Design Systems", level: 84, inDemand: true },
  { name: "Prototyping", level: 70, inDemand: false },
  { name: "Figma", level: 90, inDemand: true },
  { name: "Product Strategy", level: 76, inDemand: true },
]
